twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        app_default_theme: '%env(BACKOFFICE_DEFAULT_THEME)%'
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator


when@test:
    twig:
        strict_variables: true
