vich_uploader:
  db_driver: orm

  mappings:
    event_image:
      uri_prefix: /uploads/events
      upload_destination: '%kernel.project_dir%/public/uploads/events'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
    category_image:
      uri_prefix: /uploads/categories
      upload_destination: '%kernel.project_dir%/public/uploads/categories'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false